const STORAGE_KEY='semogogang-ckd-care-v1';
const APP_VERSION=1.1;
const metrics={creatinine:{label:'Creatinine',short:'Cr',unit:'mg/dL'},bun:{label:'BUN',short:'BUN',unit:'mg/dL'},sdma:{label:'SDMA',short:'SDMA',unit:'µg/dL'},phosphorus:{label:'Phosphorus',short:'인',unit:'mg/dL'},potassium:{label:'Potassium',short:'칼륨',unit:'mEq/L'},hct:{label:'HCT',short:'HCT',unit:'%'},upc:{label:'UPC',short:'UPC',unit:'ratio'},sbp:{label:'수축기 혈압',short:'SBP',unit:'mmHg'},weight:{label:'체중',short:'체중',unit:'kg'}};
const allLabFields=['weight','creatinine','bun','sdma','phosphorus','potassium','calcium','sodium','hct','hemoglobin','albumin','rbc','upc','usg','sbp','dbp'];
const labLabels={weight:{short:'체중',label:'체중',unit:'kg'},creatinine:{short:'Cr',label:'Creatinine',unit:'mg/dL'},bun:{short:'BUN',label:'BUN',unit:'mg/dL'},sdma:{short:'SDMA',label:'SDMA',unit:'µg/dL'},phosphorus:{short:'인',label:'Phosphorus',unit:'mg/dL'},potassium:{short:'칼륨',label:'Potassium',unit:'mEq/L'},calcium:{short:'칼슘',label:'Calcium',unit:'mg/dL'},sodium:{short:'나트륨',label:'Sodium',unit:'mEq/L'},hct:{short:'HCT',label:'HCT',unit:'%'},hemoglobin:{short:'혈색소',label:'Hemoglobin',unit:'g/dL'},albumin:{short:'Albumin',label:'Albumin',unit:'g/dL'},rbc:{short:'RBC',label:'RBC',unit:''},upc:{short:'UPC',label:'UPC',unit:'ratio'},usg:{short:'USG',label:'USG',unit:''},sbp:{short:'SBP',label:'SBP',unit:'mmHg'},dbp:{short:'DBP',label:'DBP',unit:'mmHg'}};
const periodOptions={all:'전체','3m':'최근 3개월','6m':'최근 6개월','1y':'최근 1년'};
const helpTexts={creatinine:'근육 대사 과정에서 생기는 물질로, 신장 기능 변화를 기록할 때 함께 살펴보는 검사 항목입니다.',bun:'혈액 요소질소를 뜻하며 단백질 대사와 신장 배설에 관련된 검사 항목입니다.',sdma:'신장 여과 기능 변화를 살펴볼 때 활용되는 혈액 검사 항목입니다.',phosphorus:'체내 인 농도를 나타내며 CKD 검사 기록에서 함께 추적하는 항목입니다.',potassium:'신경과 근육 기능에 관여하는 전해질의 혈중 농도입니다.',hct:'혈액에서 적혈구가 차지하는 비율을 나타내는 검사 항목입니다.',upc:'소변 단백질과 크레아티닌의 비율로, 소변 단백질 기록에 활용됩니다.',usg:'소변의 농축 정도를 나타내는 요비중 검사 항목입니다.',sbp:'심장이 수축할 때 측정되는 수축기 혈압입니다.'};
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];

function defaultState(){return{version:APP_VERSION,activePetId:'',lastBackupAt:null,pets:[],labs:[],preferences:{labPeriod:'all',chartPeriod:'all'}}}
function migrateState(raw){const base=defaultState(),source=raw&&typeof raw==='object'?raw:{},pets=Array.isArray(source.pets)?source.pets:[],labs=Array.isArray(source.labs)?source.labs:[],active=pets.some(p=>p.pet_id===source.activePetId)?source.activePetId:(pets[0]?.pet_id||''),validPeriod=value=>Object.hasOwn(periodOptions,value)?value:'all';return{...base,...source,version:APP_VERSION,pets,labs,activePetId:active,lastBackupAt:typeof source.lastBackupAt==='string'?source.lastBackupAt:null,preferences:{labPeriod:validPeriod(source.preferences?.labPeriod),chartPeriod:validPeriod(source.preferences?.chartPeriod)}}}
function load(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return defaultState()}}
let state=load(),activePetId=state.activePetId,pendingDelete='',pendingPetDelete='',detailRecordId='',chartPoints=[];
try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{}
function save(){state.activePetId=activePetId;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{showToast('브라우저 저장에 실패했습니다. JSON 백업 후 저장 공간과 개인정보 설정을 확인해 주세요.')}renderAll()}
function id(prefix){return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`}
function activePet(){return state.pets.find(p=>p.pet_id===activePetId)}
function petLabs(){return state.labs.filter(r=>r.pet_id===activePetId).sort((a,b)=>a.test_date.localeCompare(b.test_date))}
function n(value){return value===''||value==null?null:Number(value)}
function localDate(date=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date),get=type=>parts.find(p=>p.type===type)?.value;return `${get('year')}-${get('month')}-${get('day')}`}
function formatDateTime(value){if(!value)return'없음';return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))}
function fmt(value,digits=2){if(value==null||Number.isNaN(Number(value)))return'—';return Number(value).toLocaleString('ko-KR',{maximumFractionDigits:digits})}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function comparison(current,previous,key){const a=n(current?.[key]),b=n(previous?.[key]);if(a==null)return{current:'—',previous:'—',delta:null,pct:null,dir:'same',arrow:'→'};if(b==null)return{current:fmt(a),previous:'첫 기록',delta:null,pct:null,dir:'same',arrow:'·'};const delta=a-b,pct=b===0?null:delta/b*100;return{current:fmt(a),previous:fmt(b),delta,pct,dir:delta>0?'up':delta<0?'down':'same',arrow:delta>0?'↑':delta<0?'↓':'→'}}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.remove('hidden');setTimeout(()=>toast.classList.add('hidden'),3000)}
function periodRecords(records,period){if(period==='all')return records;const cutoff=new Date(`${localDate()}T00:00:00+09:00`);if(period==='3m')cutoff.setMonth(cutoff.getMonth()-3);if(period==='6m')cutoff.setMonth(cutoff.getMonth()-6);if(period==='1y')cutoff.setFullYear(cutoff.getFullYear()-1);return records.filter(record=>new Date(`${record.test_date}T00:00:00+09:00`)>=cutoff)}
function periodSelectOptions(){return Object.entries(periodOptions).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}
function setView(name){$$('.view').forEach(view=>view.classList.toggle('active',view.id===name));$$('#nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===name));$('#pageTitle').textContent={dashboard:'대시보드',pets:'반려동물 관리',labs:'검사 기록',charts:'그래프',backup:'데이터 내보내기'}[name];$('.sidebar').classList.remove('open');if(name==='charts')setTimeout(drawMainChart,20)}

function renderPetSelect(){const select=$('#activePet');select.innerHTML=state.pets.length?state.pets.map(p=>`<option value="${p.pet_id}">${p.species==='cat'?'🐱':'🐶'} ${escapeHtml(p.name)}</option>`).join(''):'<option value="">등록된 반려동물 없음</option>';select.value=activePetId}
function renderDashboard(){const pet=activePet(),labs=petLabs(),current=labs.at(-1),previous=labs.at(-2);$('#emptyState').classList.toggle('hidden',!!pet);$('#dashboardContent').classList.toggle('hidden',!pet);if(!pet)return;$('#heroSpecies').textContent=pet.species==='cat'?'🐱':'🐶';$('#heroName').textContent=pet.name;$('#heroMeta').textContent=current?`마지막 검사 ${current.test_date} · IRIS Stage ${pet.iris_stage||'미확정'} · ${fmt(current.weight??pet.weight)} kg`:`아직 검사 기록이 없습니다 · IRIS Stage ${pet.iris_stage||'미확정'}`;$('#stats').innerHTML=['creatinine','bun','sdma','phosphorus','potassium','hct','upc','sbp'].map(key=>{const c=comparison(current,previous,key),metric=metrics[key];return`<div class="stat-card"><div class="label">${metric.short} <small>${metric.unit}</small></div><div class="value ${c.dir}">${c.current} <span class="trend">${c.arrow}</span></div><div class="previous">이전 ${c.previous}${c.delta!=null?` · ${c.delta>=0?'+':''}${fmt(c.delta)}`:''}</div></div>`}).join('');$('#comparison').innerHTML=allLabFields.map(key=>{const c=comparison(current,previous,key),meta=labLabels[key];return`<div class="compare-row"><strong>${meta.short}</strong><span class="compare-values ${c.dir}">${c.previous} → ${c.current} ${c.arrow} ${c.pct==null?'':`(${c.pct>=0?'+':''}${fmt(c.pct,1)}%)`}</span></div>`}).join('');drawChart($('#miniChart'),$('#miniMetric').value||'creatinine',true)}
function renderPets(){const list=$('#petCards');list.innerHTML=state.pets.length?state.pets.map(p=>`<div class="pet-card ${p.pet_id===activePetId?'active':''}" data-pet="${p.pet_id}"><h3>${p.species==='cat'?'🐱':'🐶'} ${escapeHtml(p.name)}</h3><p>${fmt(p.weight)} kg · IRIS Stage ${p.iris_stage||'미확정'}</p><p>${escapeHtml(p.hospital||'병원 미입력')}</p><div class="pet-card-actions"><button class="secondary edit-pet" data-id="${p.pet_id}">수정</button><button class="secondary select-pet" data-id="${p.pet_id}">선택</button><button class="danger delete-pet" data-id="${p.pet_id}">삭제</button></div></div>`).join(''):'<div class="panel"><p>등록된 반려동물이 없습니다.</p></div>'}
function filteredLabs(){return periodRecords(petLabs(),state.preferences.labPeriod).sort((a,b)=>b.test_date.localeCompare(a.test_date))}
function labActionButtons(record){return`<div class="row-actions"><button data-detail-lab="${record.record_id}">상세보기</button><button data-edit-lab="${record.record_id}">수정</button><button data-delete-lab="${record.record_id}">삭제</button></div>`}
function renderLabs(){const all=petLabs(),labs=filteredLabs();$('#recordCount').textContent=labs.length===all.length?`${labs.length}건`:`${labs.length}/${all.length}건`;$('#labRows').innerHTML=labs.length?labs.map(r=>`<tr data-detail-lab="${r.record_id}" tabindex="0"><td><strong>${r.test_date}</strong></td><td>${fmt(r.creatinine)}</td><td>${fmt(r.bun)}</td><td>${fmt(r.sdma)}</td><td>${fmt(r.phosphorus)}</td><td>${fmt(r.potassium)}</td><td>${fmt(r.hct)}</td><td>${fmt(r.upc)}</td><td>${r.sbp==null?'—':fmt(r.sbp)}</td><td>${labActionButtons(r)}</td></tr>`).join(''):'<tr><td colspan="10">선택한 기간에 저장된 검사 기록이 없습니다.</td></tr>';$('#labCards').innerHTML=labs.length?labs.map(r=>`<article class="lab-card"><div><strong>${r.test_date}</strong><span>Cr ${fmt(r.creatinine)}</span></div><dl><div><dt>BUN</dt><dd>${fmt(r.bun)}</dd></div><div><dt>SDMA</dt><dd>${fmt(r.sdma)}</dd></div><div><dt>인</dt><dd>${fmt(r.phosphorus)}</dd></div></dl><button class="secondary" data-detail-lab="${r.record_id}">상세보기</button></article>`).join(''):'<p class="mobile-empty">선택한 기간에 저장된 검사 기록이 없습니다.</p>'}
function renderMetrics(){['miniMetric','chartMetric'].forEach(id=>{const element=$('#'+id),value=element.value;element.innerHTML=Object.entries(metrics).map(([key,metric])=>`<option value="${key}">${metric.label}</option>`).join('');if(value)element.value=value});['labPeriod','miniChartPeriod','chartPeriod'].forEach(id=>$('#'+id).innerHTML=periodSelectOptions());$('#labPeriod').value=state.preferences.labPeriod;$('#miniChartPeriod').value=state.preferences.chartPeriod;$('#chartPeriod').value=state.preferences.chartPeriod}
function renderBackup(){const hasLabs=state.labs.length>0;$('#lastBackup').textContent=`마지막 백업: ${formatDateTime(state.lastBackupAt)}`;$('#backupReminder').classList.toggle('hidden',!hasLabs||!!state.lastBackupAt)}
function renderAll(){renderPetSelect();renderPets();renderLabs();renderDashboard();renderBackup();if($('#charts').classList.contains('active'))drawMainChart()}

function formObject(form){return Object.fromEntries(new FormData(form).entries())}
function resetPetForm(){const form=$('#petForm');form.reset();form.pet_id.value='';form.iris_stage.value='미확정'}
function resetLabForm(){const form=$('#labForm');form.reset();form.record_id.value='';form.test_date.value=localDate()}
function fillForm(form,object){Object.entries(object).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value??''})}
function editLab(recordId){const record=state.labs.find(item=>item.record_id===recordId);if(!record)return;setView('labs');fillForm($('#labForm'),record);if($('#labDetailDialog').open)$('#labDetailDialog').close();scrollTo({top:0,behavior:'smooth'})}
function copyLatestLab(){const latest=petLabs().at(-1);if(!latest)return showToast('복사할 이전 검사 기록이 없습니다.');resetLabForm();fillForm($('#labForm'),{...latest,record_id:'',test_date:localDate(),notes:''});$('#labForm').record_id.value='';showToast('최근 검사값을 불러왔습니다. 검사일과 수치를 확인한 후 저장하세요.')}
function openLabDetail(recordId){const record=state.labs.find(item=>item.record_id===recordId);if(!record)return;detailRecordId=recordId;$('#labDetailTitle').textContent=`${record.test_date} 검사 상세보기`;const fields=[['검사일',record.test_date],...allLabFields.map(key=>[`${labLabels[key].label}${labLabels[key].unit?` (${labLabels[key].unit})`:''}`,fmt(record[key])]),['병원명',record.hospital||'—'],['메모',record.notes||'—']];$('#labDetailContent').innerHTML=fields.map(([label,value])=>`<div class="detail-item"><span>${label}</span><strong>${escapeHtml(value)}</strong></div>`).join('');$('#labDetailDialog').showModal()}
function addHelpButtons(){Object.keys(helpTexts).forEach(name=>{const input=$(`#labForm [name="${name}"]`),label=input?.closest('label');if(!label||label.querySelector('.help-btn'))return;input.setAttribute('aria-label',`${labLabels[name].label}${labLabels[name].unit?` (${labLabels[name].unit})`:''}`);const button=document.createElement('button');button.type='button';button.className='help-btn';button.dataset.help=name;button.setAttribute('aria-label',`${labLabels[name].label} 설명`);button.textContent='?';label.insertBefore(button,input)})}
function chartSummary(records,key,period){const target=records.filter(record=>n(record[key])!=null),first=target[0],last=target.at(-1),change=first&&last?comparison(last,first,key):null;return`<strong>${periodOptions[period]} · 검사 ${target.length}회</strong><span>첫 기록 ${first?fmt(first[key]):'—'}</span><span>최근 기록 ${last?fmt(last[key]):'—'}</span><span>변화 ${change?.delta!=null?`${change.delta>=0?'+':''}${fmt(change.delta)} (${change.pct>=0?'+':''}${fmt(change.pct,1)}%)`:'—'}</span>`}
function drawChart(canvas,key,mini=false){const period=state.preferences.chartPeriod,records=periodRecords(petLabs(),period).filter(record=>n(record[key])!=null),metric=metrics[key],summary=mini?$('#miniChartSummary'):$('#mainChartSummary');summary.innerHTML=chartSummary(records,key,period);if(mini){$('#miniChartTitle').textContent=metric.label;$('#miniChartEmpty').classList.toggle('hidden',records.length>=2)}else{$('#chartTitle').textContent=metric.label;$('#chartUnit').textContent=metric.unit;$('#mainChartEmpty').classList.toggle('hidden',records.length>=2)}const context=canvas.getContext('2d');context.clearRect(0,0,canvas.width,canvas.height);if(records.length<2)return;const pad=mini?45:70,width=canvas.width-pad*2,height=canvas.height-pad*1.65,values=records.map(record=>n(record[key])),min=Math.min(...values),max=Math.max(...values),range=max-min||1;context.strokeStyle='#dce8e5';context.lineWidth=1;context.fillStyle='#66807e';context.font=`${mini?18:16}px sans-serif`;for(let index=0;index<5;index++){const y=pad+height*index/4;context.beginPath();context.moveTo(pad,y);context.lineTo(pad+width,y);context.stroke();context.fillText(fmt(max-range*index/4),5,y+5)}chartPoints=[];context.strokeStyle='#167d74';context.lineWidth=4;context.beginPath();records.forEach((record,index)=>{const x=pad+width*index/(records.length-1),y=pad+height*(max-n(record[key]))/range;index?context.lineTo(x,y):context.moveTo(x,y);chartPoints.push({x:x*canvas.clientWidth/canvas.width,y:y*canvas.clientHeight/canvas.height,date:record.test_date,value:n(record[key]),key})});context.stroke();records.forEach((record,index)=>{const x=pad+width*index/(records.length-1),y=pad+height*(max-n(record[key]))/range;context.beginPath();context.arc(x,y,6,0,Math.PI*2);context.fillStyle='#fff';context.fill();context.strokeStyle='#167d74';context.lineWidth=4;context.stroke();context.fillStyle='#66807e';context.fillText(record.test_date.slice(5),x-24,pad+height+32)})}
function drawMainChart(){drawChart($('#mainChart'),$('#chartMetric').value||'creatinine')}
function download(name,text,type){const anchor=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));anchor.href=url;anchor.download=name;anchor.style.display='none';document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast(`${name} 다운로드를 시작했습니다.`)}
function implausibleValues(values){const limits={weight:200,creatinine:100,bun:1000,sdma:1000,phosphorus:100,potassium:50,calcium:100,sodium:300,hct:100,hemoglobin:50,rbc:50,upc:100,usg:2,sbp:400,dbp:300};return Object.entries(limits).filter(([key,max])=>values[key]!=null&&Number(values[key])>max).map(([key])=>key)}
function confirmImplausible(fields){if(!fields.length)return true;showToast(`입력값을 다시 확인하세요: ${fields.join(', ')}`);return window.confirm(`입력값을 다시 확인하세요.\n\n확인 필요 항목: ${fields.join(', ')}\n\n임상 판정이 아닌 입력 오류 방지 경고입니다. 그래도 저장하시겠습니까?`)}
function csv(){const rows=petLabs(),pet=activePet();if(!pet||!rows.length)return showToast('내보낼 검사 기록이 없습니다.');const columns=['test_date',...allLabFields,'hospital','notes'],escape=value=>`"${String(value??'').replaceAll('"','""')}"`;download(`${pet.name}_검사기록.csv`,'\uFEFF'+[columns.join(','),...rows.map(row=>columns.map(column=>escape(row[column])).join(','))].join('\r\n'),'text/csv;charset=utf-8')}
function exportJson(){state.lastBackupAt=new Date().toISOString();save();const payload={app:'semogogang-ckd-care',version:APP_VERSION,exported_at:state.lastBackupAt,activePetId,pets:state.pets,labs:state.labs,preferences:state.preferences};download(`세모고강_CKD_백업_${localDate()}.json`,JSON.stringify(payload,null,2),'application/json')}

$('#nav').addEventListener('click',event=>{const button=event.target.closest('button[data-view]');if(button)setView(button.dataset.view)});
document.addEventListener('click',event=>{const go=event.target.closest('[data-go]');if(go)setView(go.dataset.go);const card=event.target.closest('.pet-card');if(card&&!event.target.closest('button')){activePetId=card.dataset.pet;save()}const editPetButton=event.target.closest('.edit-pet');if(editPetButton){const pet=state.pets.find(item=>item.pet_id===editPetButton.dataset.id);fillForm($('#petForm'),pet);scrollTo({top:0,behavior:'smooth'})}const selectPetButton=event.target.closest('.select-pet');if(selectPetButton){activePetId=selectPetButton.dataset.id;save();showToast('반려동물을 선택했습니다.')}const deletePetButton=event.target.closest('.delete-pet');if(deletePetButton){const pet=state.pets.find(item=>item.pet_id===deletePetButton.dataset.id),count=state.labs.filter(record=>record.pet_id===pet.pet_id).length;pendingPetDelete=pet.pet_id;$('#petDeleteTitle').textContent=`${pet.name}을 삭제하시겠습니까?`;$('#petDeleteCount').textContent=`이 반려동물과 연결된 검사 기록 ${count}건도 함께 삭제됩니다.`;$('#petDeleteDialog').showModal()}const detailButton=event.target.closest('[data-detail-lab]');if(detailButton&&!event.target.closest('[data-edit-lab],[data-delete-lab]'))openLabDetail(detailButton.dataset.detailLab);const editLabButton=event.target.closest('[data-edit-lab]');if(editLabButton){event.stopPropagation();editLab(editLabButton.dataset.editLab)}const deleteLabButton=event.target.closest('[data-delete-lab]');if(deleteLabButton){event.stopPropagation();pendingDelete=deleteLabButton.dataset.deleteLab;$('#confirmDialog').showModal()}const helpButton=event.target.closest('[data-help]');if(helpButton){const key=helpButton.dataset.help;$('#helpTitle').textContent=`${labLabels[key].label} 도움말`;$('#helpText').textContent=helpTexts[key];$('#helpDialog').showModal()}});
document.addEventListener('keydown',event=>{const row=event.target.closest('tr[data-detail-lab]');if(row&&(event.key==='Enter'||event.key===' ')){event.preventDefault();openLabDetail(row.dataset.detailLab)}});
$('#activePet').addEventListener('change',event=>{activePetId=event.target.value;save()});$('#menuBtn').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));$('#newPetBtn').onclick=resetPetForm;$('#newLabBtn').onclick=resetLabForm;$('#copyLabBtn').onclick=copyLatestLab;
$('#petForm').addEventListener('submit',event=>{event.preventDefault();const object=formObject(event.currentTarget);if(n(object.weight)<=0)return showToast('체중은 0보다 커야 합니다.');object.weight=n(object.weight);const warnings=implausibleValues(object);if(!confirmImplausible(warnings))return;const existing=object.pet_id&&state.pets.find(p=>p.pet_id===object.pet_id),pet={...existing,...object,pet_id:object.pet_id||id('pet'),updated_at:new Date().toISOString()};state.pets=existing?state.pets.map(item=>item.pet_id===pet.pet_id?pet:item):[...state.pets,pet];activePetId=pet.pet_id;resetPetForm();save();showToast(warnings.length?'입력값 경고를 확인하고 반려동물 정보를 저장했습니다.':'반려동물 정보를 저장했습니다.')});
$('#labForm').addEventListener('submit',event=>{event.preventDefault();if(!activePet())return showToast('먼저 반려동물을 등록해 주세요.');const object=formObject(event.currentTarget);allLabFields.forEach(key=>object[key]=n(object[key]));const existing=object.record_id&&state.labs.find(record=>record.record_id===object.record_id);if(!allLabFields.some(key=>object[key]!=null))return showToast('검사값을 하나 이상 입력해 주세요.');if(state.labs.some(record=>record.pet_id===activePetId&&record.test_date===object.test_date&&record.record_id!==object.record_id))return showToast('같은 날짜의 검사 기록이 이미 있습니다. 기존 기록을 수정해 주세요.');const warnings=implausibleValues(object);if(!confirmImplausible(warnings))return;const record={...existing,...object,record_id:object.record_id||id('lab'),pet_id:activePetId,created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};state.labs=existing?state.labs.map(item=>item.record_id===record.record_id?record:item):[...state.labs,record];resetLabForm();save();showToast(warnings.length?'입력값 경고를 확인하고 검사 기록을 저장했습니다.':'검사 기록을 저장했습니다.')});
$('#cancelDelete').onclick=()=>$('#confirmDialog').close();$('#confirmDelete').onclick=()=>{state.labs=state.labs.filter(record=>record.record_id!==pendingDelete);pendingDelete='';$('#confirmDialog').close();save();showToast('검사 기록을 삭제했습니다.')};
$('#cancelPetDelete').onclick=()=>$('#petDeleteDialog').close();$('#confirmPetDelete').onclick=()=>{const pet=state.pets.find(item=>item.pet_id===pendingPetDelete),name=pet?.name||'반려동물';state.pets=state.pets.filter(item=>item.pet_id!==pendingPetDelete);state.labs=state.labs.filter(record=>record.pet_id!==pendingPetDelete);activePetId=state.pets[0]?.pet_id||'';pendingPetDelete='';$('#petDeleteDialog').close();resetPetForm();save();showToast(`${name}과 연결된 검사 기록을 삭제했습니다.`)};
$('#closeLabDetail').onclick=$('#closeLabDetailBottom').onclick=()=>$('#labDetailDialog').close();$('#editLabFromDetail').onclick=()=>editLab(detailRecordId);$('#closeHelp').onclick=()=>$('#helpDialog').close();$('#miniMetric').onchange=renderDashboard;$('#chartMetric').onchange=drawMainChart;
$('#labPeriod').onchange=event=>{state.preferences.labPeriod=event.target.value;save()};function updateChartPeriod(value){state.preferences.chartPeriod=value;$('#miniChartPeriod').value=value;$('#chartPeriod').value=value;save()}$('#miniChartPeriod').onchange=event=>updateChartPeriod(event.target.value);$('#chartPeriod').onchange=event=>updateChartPeriod(event.target.value);
$('#csvExport').onclick=csv;$('#jsonExport').onclick=exportJson;
$('#jsonImport').addEventListener('change',async event=>{try{if((state.pets.length||state.labs.length)&&!window.confirm('복원하면 현재 브라우저 데이터가 백업 내용으로 교체됩니다. 기존 데이터를 먼저 JSON으로 백업했는지 확인해 주세요. 계속하시겠습니까?'))return;const data=JSON.parse(await event.target.files[0].text());if(!Array.isArray(data.pets)||!Array.isArray(data.labs))throw Error();state=migrateState(data);activePetId=state.activePetId;save();showToast(`v${data.version||'1.0'} 백업 데이터를 복원했습니다.`)}catch{showToast('올바른 백업 파일이 아닙니다.')}finally{event.target.value=''}});
$('#mainChart').addEventListener('mousemove',event=>{const rect=event.currentTarget.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,point=chartPoints.find(item=>Math.hypot(item.x-x,item.y-y)<16),tooltip=$('#tooltip');if(!point)return tooltip.classList.add('hidden');tooltip.textContent=`${point.date} · ${fmt(point.value)} ${metrics[point.key].unit}`;tooltip.style.left=`${point.x}px`;tooltip.style.top=`${point.y}px`;tooltip.classList.remove('hidden')});$('#mainChart').addEventListener('mouseleave',()=>$('#tooltip').classList.add('hidden'));
renderMetrics();resetLabForm();addHelpButtons();renderAll();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
