const STORAGE_KEY='semogogang-ckd-care-v1';
const metrics={creatinine:{label:'Creatinine',short:'Cr',unit:'mg/dL'},bun:{label:'BUN',short:'BUN',unit:'mg/dL'},sdma:{label:'SDMA',short:'SDMA',unit:'µg/dL'},phosphorus:{label:'Phosphorus',short:'인',unit:'mg/dL'},potassium:{label:'Potassium',short:'칼륨',unit:'mEq/L'},hct:{label:'HCT',short:'HCT',unit:'%'},upc:{label:'UPC',short:'UPC',unit:'ratio'},sbp:{label:'수축기 혈압',short:'SBP',unit:'mmHg'},weight:{label:'체중',short:'체중',unit:'kg'}};
const allLabFields=['weight','creatinine','bun','sdma','phosphorus','potassium','calcium','sodium','hct','hemoglobin','albumin','rbc','upc','usg','sbp','dbp'];
const labLabels={weight:{short:'체중',unit:'kg'},creatinine:{short:'Cr',unit:'mg/dL'},bun:{short:'BUN',unit:'mg/dL'},sdma:{short:'SDMA',unit:'µg/dL'},phosphorus:{short:'인',unit:'mg/dL'},potassium:{short:'칼륨',unit:'mEq/L'},calcium:{short:'칼슘',unit:'mg/dL'},sodium:{short:'나트륨',unit:'mEq/L'},hct:{short:'HCT',unit:'%'},hemoglobin:{short:'혈색소',unit:'g/dL'},albumin:{short:'Albumin',unit:'g/dL'},rbc:{short:'RBC',unit:''},upc:{short:'UPC',unit:'ratio'},usg:{short:'USG',unit:''},sbp:{short:'SBP',unit:'mmHg'},dbp:{short:'DBP',unit:'mmHg'}};
let state=load();let activePetId=state.activePetId||state.pets[0]?.pet_id||'';let pendingDelete='';let chartPoints=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{version:1,pets:[],labs:[]}}catch{return{version:1,pets:[],labs:[]}}}
function save(){state.activePetId=activePetId;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{showToast('브라우저 저장에 실패했습니다. JSON 백업 후 저장 공간과 개인정보 설정을 확인해 주세요.')}renderAll()}
function id(prefix){return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`}
function activePet(){return state.pets.find(p=>p.pet_id===activePetId)}
function petLabs(){return state.labs.filter(r=>r.pet_id===activePetId).sort((a,b)=>a.test_date.localeCompare(b.test_date))}
function n(v){return v===''||v==null?null:Number(v)}
function fmt(v,d=2){if(v==null||Number.isNaN(Number(v)))return '—';return Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d})}
function comparison(cur,prev,key){const a=n(cur?.[key]),b=n(prev?.[key]);if(a==null)return{current:'—',previous:'—',delta:null,pct:null,dir:'same',arrow:'→'};if(b==null)return{current:fmt(a),previous:'첫 기록',delta:null,pct:null,dir:'same',arrow:'·'};const d=a-b,p=b===0?null:d/b*100;return{current:fmt(a),previous:fmt(b),delta:d,pct:p,dir:d>0?'up':d<0?'down':'same',arrow:d>0?'↑':d<0?'↓':'→'}}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2400)}
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent={dashboard:'대시보드',pets:'반려동물 관리',labs:'검사 기록',charts:'그래프',backup:'데이터 내보내기'}[name];$('.sidebar').classList.remove('open');if(name==='charts')setTimeout(()=>drawMainChart(),20)}
function renderPetSelect(){const s=$('#activePet');s.innerHTML=state.pets.length?state.pets.map(p=>`<option value="${p.pet_id}">${p.species==='cat'?'🐱':'🐶'} ${escapeHtml(p.name)}</option>`).join(''):'<option value="">등록된 반려동물 없음</option>';s.value=activePetId}
function renderDashboard(){const pet=activePet(),labs=petLabs(),cur=labs.at(-1),prev=labs.at(-2);$('#emptyState').classList.toggle('hidden',!!pet);$('#dashboardContent').classList.toggle('hidden',!pet);if(!pet)return;$('#heroSpecies').textContent=pet.species==='cat'?'🐱':'🐶';$('#heroName').textContent=pet.name;$('#heroMeta').textContent=cur?`마지막 검사 ${cur.test_date} · IRIS Stage ${pet.iris_stage||'미확정'} · ${fmt(cur.weight??pet.weight)} kg`:`아직 검사 기록이 없습니다 · IRIS Stage ${pet.iris_stage||'미확정'}`;const keys=['creatinine','bun','sdma','phosphorus','potassium','hct','upc','sbp'];$('#stats').innerHTML=keys.map(k=>{const c=comparison(cur,prev,k),m=metrics[k]||{short:k,unit:''};return `<div class="stat-card"><div class="label">${m.short} <small>${m.unit}</small></div><div class="value ${c.dir}">${c.current} <span class="trend">${c.arrow}</span></div><div class="previous">이전 ${c.previous}${c.delta!=null?` · ${c.delta>=0?'+':''}${fmt(c.delta)}`:''}</div></div>`}).join('');$('#comparison').innerHTML=allLabFields.map(k=>{const c=comparison(cur,prev,k),m=labLabels[k];return `<div class="compare-row"><strong>${m.short}</strong><span class="compare-values ${c.dir}">${c.previous} → ${c.current} ${c.arrow} ${c.pct==null?'':`(${c.pct>=0?'+':''}${fmt(c.pct,1)}%)`}</span></div>`}).join('')||'<p>저장된 검사 기록이 없습니다.</p>';drawChart($('#miniChart'),$('#miniMetric').value||'creatinine',true)}
function renderPets(){const list=$('#petCards');list.innerHTML=state.pets.length?state.pets.map(p=>`<div class="pet-card ${p.pet_id===activePetId?'active':''}" data-pet="${p.pet_id}"><h3>${p.species==='cat'?'🐱':'🐶'} ${escapeHtml(p.name)}</h3><p>${fmt(p.weight)} kg · IRIS Stage ${p.iris_stage||'미확정'}</p><p>${escapeHtml(p.hospital||'병원 미입력')}</p><div class="pet-card-actions"><button class="secondary edit-pet" data-id="${p.pet_id}">수정</button><button class="secondary select-pet" data-id="${p.pet_id}">선택</button></div></div>`).join(''):'<div class="panel"><p>등록된 반려동물이 없습니다.</p></div>'}
function renderLabs(){const labs=petLabs().sort((a,b)=>b.test_date.localeCompare(a.test_date));$('#recordCount').textContent=`${labs.length}건`;$('#labRows').innerHTML=labs.length?labs.map(r=>`<tr><td><strong>${r.test_date}</strong></td><td>${fmt(r.creatinine)}</td><td>${fmt(r.bun)}</td><td>${fmt(r.sdma)}</td><td>${fmt(r.phosphorus)}</td><td>${fmt(r.potassium)}</td><td>${fmt(r.hct)}</td><td>${fmt(r.upc)}</td><td>${r.sbp==null?'—':fmt(r.sbp)}</td><td><div class="row-actions"><button data-edit-lab="${r.record_id}">수정</button><button data-delete-lab="${r.record_id}">삭제</button></div></td></tr>`).join(''):'<tr><td colspan="10">아직 저장된 검사 기록이 없습니다.</td></tr>'}
function renderMetrics(){['miniMetric','chartMetric'].forEach(id=>{const el=$('#'+id),val=el.value;el.innerHTML=Object.entries(metrics).map(([k,m])=>`<option value="${k}">${m.label}</option>`).join('');if(val)el.value=val});}
function renderAll(){renderPetSelect();renderPets();renderLabs();renderDashboard();if($('#charts').classList.contains('active'))drawMainChart()}
function formObject(form){return Object.fromEntries(new FormData(form).entries())}
function resetPetForm(){const f=$('#petForm');f.reset();f.pet_id.value='';f.iris_stage.value='미확정'}
function resetLabForm(){const f=$('#labForm');f.reset();f.record_id.value='';f.test_date.value=new Date().toISOString().slice(0,10)}
function fillForm(form,obj){Object.entries(obj).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v??''})}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function drawChart(canvas,key,mini=false){const ctx=canvas.getContext('2d'),records=petLabs().filter(r=>n(r[key])!=null),m=metrics[key];if(mini){$('#miniChartTitle').textContent=m.label;$('#miniChartEmpty').classList.toggle('hidden',records.length>=2)}else{$('#chartTitle').textContent=m.label;$('#chartUnit').textContent=m.unit;$('#mainChartEmpty').classList.toggle('hidden',records.length>=2)}ctx.clearRect(0,0,canvas.width,canvas.height);if(records.length<2)return;const pad=mini?45:70,w=canvas.width-pad*2,h=canvas.height-pad*1.65,vals=records.map(r=>n(r[key])),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;ctx.strokeStyle='#dce8e5';ctx.lineWidth=1;ctx.fillStyle='#66807e';ctx.font=`${mini?18:16}px sans-serif`;for(let i=0;i<5;i++){const y=pad+h*i/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(pad+w,y);ctx.stroke();ctx.fillText(fmt(max-range*i/4),5,y+5)}chartPoints=[];ctx.strokeStyle='#167d74';ctx.lineWidth=4;ctx.beginPath();records.forEach((r,i)=>{const x=pad+w*i/(records.length-1),y=pad+h*(max-n(r[key]))/range;i?ctx.lineTo(x,y):ctx.moveTo(x,y);chartPoints.push({x:x*canvas.clientWidth/canvas.width,y:y*canvas.clientHeight/canvas.height,date:r.test_date,value:n(r[key]),key})});ctx.stroke();records.forEach((r,i)=>{const x=pad+w*i/(records.length-1),y=pad+h*(max-n(r[key]))/range;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#167d74';ctx.lineWidth=4;ctx.stroke();const label=r.test_date.slice(5);ctx.fillStyle='#66807e';ctx.fillText(label,x-24,pad+h+32)})}
function drawMainChart(){drawChart($('#mainChart'),$('#chartMetric').value||'creatinine')}
function download(name,text,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast(`${name} 다운로드를 시작했습니다.`)}
function implausibleValues(values){const limits={weight:200,creatinine:100,bun:1000,sdma:1000,phosphorus:100,potassium:50,calcium:100,sodium:300,hct:100,hemoglobin:50,rbc:50,upc:100,usg:2,sbp:400,dbp:300};return Object.entries(limits).filter(([key,max])=>values[key]!=null&&Number(values[key])>max).map(([key])=>key)}
function confirmImplausible(fields){if(!fields.length)return true;showToast(`입력값을 다시 확인하세요: ${fields.join(', ')}`);return window.confirm(`입력값을 다시 확인하세요.\n\n확인 필요 항목: ${fields.join(', ')}\n\n임상 판정이 아닌 입력 오류 방지 경고입니다. 그래도 저장하시겠습니까?`)}
function csv(){const rows=petLabs(),pet=activePet();if(!pet||!rows.length)return showToast('내보낼 검사 기록이 없습니다.');const cols=['test_date',...allLabFields,'hospital','notes'];const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;download(`${pet.name}_검사기록.csv`,'\uFEFF'+[cols.join(','),...rows.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\r\n'),'text/csv;charset=utf-8')}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)setView(b.dataset.view)});document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g)setView(g.dataset.go);const pc=e.target.closest('.pet-card');if(pc&&!e.target.closest('button')){activePetId=pc.dataset.pet;save()}const ep=e.target.closest('.edit-pet');if(ep){const p=state.pets.find(x=>x.pet_id===ep.dataset.id);fillForm($('#petForm'),p);scrollTo({top:0,behavior:'smooth'})}const sp=e.target.closest('.select-pet');if(sp){activePetId=sp.dataset.id;save();showToast('반려동물을 선택했습니다.')}const el=e.target.closest('[data-edit-lab]');if(el){const r=state.labs.find(x=>x.record_id===el.dataset.editLab);fillForm($('#labForm'),r);scrollTo({top:0,behavior:'smooth'})}const dl=e.target.closest('[data-delete-lab]');if(dl){pendingDelete=dl.dataset.deleteLab;$('#confirmDialog').showModal()}});
$('#activePet').addEventListener('change',e=>{activePetId=e.target.value;save()});$('#menuBtn').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));$('#newPetBtn').onclick=resetPetForm;$('#newLabBtn').onclick=resetLabForm;
$('#petForm').addEventListener('submit',e=>{e.preventDefault();const o=formObject(e.currentTarget);if(n(o.weight)<=0)return showToast('체중은 0보다 커야 합니다.');o.weight=n(o.weight);const warnings=implausibleValues(o);if(!confirmImplausible(warnings))return;const existing=o.pet_id&&state.pets.find(p=>p.pet_id===o.pet_id);const p={...existing,...o,pet_id:o.pet_id||id('pet'),updated_at:new Date().toISOString()};if(existing)state.pets=state.pets.map(x=>x.pet_id===p.pet_id?p:x);else state.pets.push(p);activePetId=p.pet_id;resetPetForm();save();showToast(warnings.length?'입력값 경고를 확인하고 반려동물 정보를 저장했습니다.':'반려동물 정보를 저장했습니다.')});
$('#labForm').addEventListener('submit',e=>{e.preventDefault();if(!activePet())return showToast('먼저 반려동물을 등록해 주세요.');const o=formObject(e.currentTarget);allLabFields.forEach(k=>o[k]=n(o[k]));const existing=o.record_id&&state.labs.find(r=>r.record_id===o.record_id);if(!allLabFields.some(k=>o[k]!=null))return showToast('검사값을 하나 이상 입력해 주세요.');if(state.labs.some(r=>r.pet_id===activePetId&&r.test_date===o.test_date&&r.record_id!==o.record_id))return showToast('같은 날짜의 검사 기록이 이미 있습니다. 기존 기록을 수정해 주세요.');const warnings=implausibleValues(o);if(!confirmImplausible(warnings))return;const r={...existing,...o,record_id:o.record_id||id('lab'),pet_id:activePetId,created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};if(existing)state.labs=state.labs.map(x=>x.record_id===r.record_id?r:x);else state.labs.push(r);resetLabForm();save();showToast(warnings.length?'입력값 경고를 확인하고 검사 기록을 저장했습니다.':'검사 기록을 저장했습니다.')});
$('#cancelDelete').onclick=()=>$('#confirmDialog').close();$('#confirmDelete').onclick=()=>{state.labs=state.labs.filter(r=>r.record_id!==pendingDelete);pendingDelete='';$('#confirmDialog').close();save();showToast('검사 기록을 삭제했습니다.')};
$('#miniMetric').onchange=renderDashboard;$('#chartMetric').onchange=drawMainChart;$('#csvExport').onclick=csv;$('#jsonExport').onclick=()=>download(`세모고강_CKD_백업_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({...state,exported_at:new Date().toISOString()},null,2),'application/json');$('#jsonImport').addEventListener('change',async e=>{try{if((state.pets.length||state.labs.length)&&!window.confirm('복원하면 현재 브라우저 데이터가 백업 내용으로 교체됩니다. 기존 데이터를 먼저 JSON으로 백업했는지 확인해 주세요. 계속하시겠습니까?'))return;const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.pets)||!Array.isArray(data.labs))throw Error();state={version:1,pets:data.pets,labs:data.labs};activePetId=state.pets[0]?.pet_id||'';save();showToast('백업 데이터를 복원했습니다.')}catch{showToast('올바른 백업 파일이 아닙니다.')}finally{e.target.value=''}});
$('#mainChart').addEventListener('mousemove',e=>{const rect=e.currentTarget.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,p=chartPoints.find(p=>Math.hypot(p.x-x,p.y-y)<16),t=$('#tooltip');if(!p)return t.classList.add('hidden');t.textContent=`${p.date} · ${fmt(p.value)} ${metrics[p.key].unit}`;t.style.left=`${p.x}px`;t.style.top=`${p.y}px`;t.classList.remove('hidden')});$('#mainChart').addEventListener('mouseleave',()=>$('#tooltip').classList.add('hidden'));
renderMetrics();resetLabForm();renderAll();
